import type { Container, RecyclingPoint } from '../types/index'
import { DATA_PATHS } from '../constants/index'

/**
 * Fetch all containers from the generated JSON file
 * Returns empty array if fetch fails
 */
export async function fetchContainers(): Promise<Container[]> {
  try {
    const response = await fetch(DATA_PATHS.CONTAINERS)
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`)
    }
    const data = await response.json()
    return Array.isArray(data) ? data : []
  } catch {
    return []
  }
}

/**
 * Fetch all recycling points from the generated JSON file
 * Returns empty array if fetch fails
 */
export async function fetchRecyclingPoints(): Promise<RecyclingPoint[]> {
  try {
    const response = await fetch(DATA_PATHS.RECICLAJE)
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`)
    }
    const data = await response.json()
    return Array.isArray(data) ? data : []
  } catch {
    return []
  }
}

/**
 * Fetch metadata about the last data update
 * lastUpdate comes from the JSON generated by GitHub Actions
 */
export async function fetchDataInfo(): Promise<{ lastUpdate: string; total: number }> {
  try {
    const containers = await fetchContainers()
    return {
      lastUpdate: containers[0]?.dateData ?? '',
      total: containers.length,
    }
  } catch {
    return {
      lastUpdate: '',
      total: 0,
    }
  }
}